name: Build and deploy dotnet core app to Azure Function App - azurlshortenerfuncapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/AzUrlShortener.Functions' # updated to the actual project path
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore & Build Project'
        shell: pwsh
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9988AA632E564F79A8FD1CDBEB7A44E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D62330B060674C7289BA101D01B86645 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_828732824D6B4419B42E03476C189EF0 }}

      - name: 'Deploy to Azure Function'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'azurlshortenerfuncapp'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
